---
- name: Get Openshift playbook from repo
  git:
      repo: "https://github.com/openshift/openshift-ansible.git"
      dest: /tmp/openshift-ansible
      version: "{{ openshift_version }}"
  when: perform_openshift_installation == True

- name: Run Openshift installation prerequisit
  command: "ansible-playbook -i {{ host_path }}/hosts /tmp/openshift-ansible/playbooks/prerequisites.yml"
  when: perform_openshift_installation == True

- name: Run Openshift installation
  command: "ansible-playbook -i {{ host_path }}/hosts /tmp/openshift-ansible/playbooks/deploy_cluster.yml"
  when: perform_openshift_installation == True

- name: Restart Openshift node service
  command: "systemctl restart atomic-openshift-master-api atomic-openshift-master-controllers"
  when: perform_openshift_installation == False
